pipeline {
  agent none
  stages {
    stage('Docker Build') {
      agent any
      steps {
        sh 'sudo docker build -t vikson36/bb-app:${BUILD_NUMBER} ${WORKSPACE}/bulletin-board-app'
      }
    }
    stage('Docker Push') {
      agent any
      steps {
        sh 'sudo docker push vikson36/bb-app:${BUILD_NUMBER}'
      }
    }
  }
}
