pipeline {
  agent none
  stages {
    stage('Docker Build') {
      agent any
      steps {
        sh 'sudo docker build -t vikson36/bb-app:${BUILD_NUMBER} ${WORKSPACE}/bulletin-board-app'
      }
    }
	stage('Docker Push') {
      agent any
      steps {
        sh 'sudo docker push vikson36/bb-app:${BUILD_NUMBER}'
      }
    }
	
  }
  agent {docker_dev}
  stages {
     stage('Docker pull') {
	     agent any
         steps {
         sh 'sudo docker pull vikson36/bb-app:${BUILD_NUMBER}'
      }
    }
	stage('Docker run') {
         agent any
         steps {
         sh 'sudo docker container run --detach --publish 8080:8080 vikson36/bb-app:${BUILD_NUMBER}'
      }
    }
  
  
  }
   
}
