version: '3.3'

services:
      
  bb-db:
    image: bulletin-board-db:v3
    build:
      context: ./bulletin-board-db
    networks:
      - bb-net

  bb-app:
    image: bulletin-board-app:v3
    build:
      context: ./bulletin-board-app
    depends_on:
      - bb-db
    restart: on-failure
    networks:
      - bb-net

networks:
  bb-net: