version: '3.3'

services:
      
  bb-db:
    image: ${dockerId}/bulletin-board-db:v3
    networks:
      - bb-net

  bb-app:
    image: ${dockerId}/bulletin-board-app:v3
    ports:
      - "8080:8080"
    networks:
      - bb-net

networks:
  bb-net: